version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
